name: Auto Tagger

on:
  workflow_call:

jobs:
  build:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: RueLaLa/auto-tagger@master
        env:
          GITHUB_PR_NUMBER: ${{ github.event.number }}
